# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=30

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never

# server port
server.port=8080

# security
jwt.secret.key=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkey
jwt.refresh.expiration.time=2592000000
jwt.access.expiration.time=43200000