server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_lms
spring.datasource.username=postgres
spring.datasource.password=xush2004@

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkey
jwt.refresh.expiration.time=2592000000
jwt.access.expiration.time=43200000

server.forward-headers-strategy=framework

spring.sql.init.mode=never